In [1]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('default')

from warnings import filterwarnings
filterwarnings("ignore")

from math import sqrt
from scipy.stats import\
    ttest_ind as t_Test,\
    f_oneway as f_Test
from sklearn.metrics import\
    mean_squared_error as MSE,\
    mean_absolute_error as MAE,\
    r2_score as R2

In [2]:
# use pd.merge to get comparison table with timestamps instead of pulling from DW
import os
current_dir = os.getcwd()

esolat_dir = current_dir + "\\data extraction and cleanup\\esolat2018to2025.csv"
esolatDF = pd.read_csv(esolat_dir)
esolatDate = pd.to_datetime(esolatDF["date"]).dt.date
esolatFajr = pd.to_datetime(esolatDF["fajr"], format="%H:%M:%S").dt.strftime("%H:%M")
esolatZuhr = pd.to_datetime(esolatDF["zuhr"], format="%H:%M:%S").dt.strftime("%H:%M")
esolatAsr = pd.to_datetime(esolatDF["asr"], format="%H:%M:%S").dt.strftime("%H:%M")
esolatMaghrib = pd.to_datetime(esolatDF["maghrib"], format="%H:%M:%S").dt.strftime("%H:%M")
esolatIsha = pd.to_datetime(esolatDF["isha"], format="%H:%M:%S").dt.strftime("%H:%M")
copiedEsolatDF = \
    pd.DataFrame(
        [esolatDate,esolatFajr,esolatZuhr,esolatAsr,esolatMaghrib,esolatIsha]
    ).transpose()

google_dir = current_dir + "\\data extraction and cleanup\\htmldata\\googlesearch_2024_12.txt"
googleDF = pd.read_html(google_dir)[0]
googleDF[0][0] = "2024"
googleDF[3][0] = "Zuhr"
googleDF.columns = googleDF.iloc[0]
googleDF = googleDF[1:].reset_index(drop=True)
googleDate = pd.to_datetime(googleDF["2024"].astype(str) + " 2024", format="%d %b %Y").dt.date
googleFajr = pd.to_datetime(googleDF["Fajr"], format="%H:%M").dt.strftime("%H:%M")
googleZuhr = pd.to_datetime(googleDF["Zuhr"], format="%H:%M").dt.strftime("%H:%M")
googleAsr = pd.to_datetime(googleDF["Asr"], format="%H:%M").dt.strftime("%H:%M")
googleMaghrib = pd.to_datetime(googleDF["Maghrib"], format="%H:%M").dt.strftime("%H:%M")
googleIsha = pd.to_datetime(googleDF["Isha"], format="%H:%M").dt.strftime("%H:%M")
copiedGoogleDF = \
    pd.DataFrame(
        [googleDate,googleFajr,googleZuhr,googleAsr,googleMaghrib,googleIsha]
    ).transpose()

combinationTable = copiedEsolatDF.merge(
    copiedGoogleDF,
    how="inner",
    left_on="date",
    right_on="2024"
)
combinationTable = combinationTable[
    ["date","fajr","Fajr","zuhr","Zuhr","asr","Asr","maghrib","Maghrib","isha","Isha"]
]
new_col_name = {
    "fajr": "esolat_fajr",
    "Fajr": "google_fajr",
    "zuhr": "esolat_zuhr",
    "Zuhr": "google_zuhr",
    "asr": "esolat_asr",
    "Asr": "google_asr",
    "maghrib": "esolat_maghrib",
    "Maghrib": "google_maghrib",
    "isha": "esolat_isha",
    "Isha": "google_isha"
}
combinationTable.rename(columns=new_col_name, inplace=True)

combinationTable

,date,esolat_fajr,google_fajr,esolat_zuhr,google_zuhr,esolat_asr,google_asr,esolat_maghrib,google_maghrib,esolat_isha,google_isha
0,2024-11-30,05:52,05:52,13:05,13:03,16:27,16:27,19:02,19:02,20:16,20:16
1,2024-12-01,05:52,05:52,13:05,13:03,16:28,16:27,19:02,19:02,20:17,20:16
2,2024-12-02,05:53,05:52,13:05,13:04,16:28,16:28,19:03,19:02,20:17,20:17
3,2024-12-03,05:53,05:53,13:06,13:04,16:28,16:28,19:03,19:03,20:17,20:17
4,2024-12-04,05:53,05:53,13:06,13:04,16:29,16:29,19:04,19:03,20:18,20:17
5,2024-12-05,05:54,05:53,13:07,13:05,16:29,16:29,19:04,19:03,20:18,20:18
6,2024-12-06,05:54,05:54,13:07,13:05,16:30,16:29,19:04,19:04,20:19,20:18
7,2024-12-07,05:55,05:54,13:08,13:06,16:30,16:30,19:05,19:04,20:19,20:19
8,2024-12-08,05:55,05:55,13:08,13:06,16:31,16:30,19:05,19:05,20:20,20:19
9,2024-12-09,05:55,05:55,13:08,13:06,16:31,16:31,19:06,19:05,20:20,20:20
10,2024-12-10,05:56,05:55,13:09,13:07,16:31,16:31,19:06,19:06,20:21,20:20
11,2024-12-11,05:56,05:56,13:09,13:07,16:32,16:32,19:06,19:06,20:21,20:21
12,2024-12-12,05:57,05:56,13:10,13:08,16:32,16:32,19:07,19:06,20:22,20:21
13,2024-12-13,05:57,05:57,13:10,13:08,16:33,16:33,19:07,19:07,20:22,20:22
14,2024-12-14,05:58,05:57,13:11,13:09,16:33,16:33,19:08,19:07,20:23,20:22
15,2024-12-15,05:58,05:58,13:11,13:09,16:34,16:34,19:08,19:08,20:23,20:23
16,2024-12-16,05:59,05:58,13:12,13:10,16:34,16:34,19:09,19:08,20:24,20:23
17,2024-12-17,05:59,05:58,13:12,13:10,16:35,16:35,19:09,19:09,20:24,20:24
18,2024-12-18,06:00,05:59,13:13,13:11,16:35,16:35,19:10,19:09,20:25,20:24
19,2024-12-19,06:00,05:59,13:13,13:11,16:36,16:36,19:10,19:10,20:25,20:25
20,2024-12-20,06:01,06:00,13:14,13:12,16:36,16:36,19:11,19:10,20:26,20:25
21,2024-12-21,06:01,06:00,13:14,13:12,16:37,16:37,19:11,19:11,20:26,20:26
22,2024-12-22,06:02,06:01,13:15,13:13,16:37,16:37,19:12,19:11,20:27,20:26
23,2024-12-23,06:02,06:01,13:15,13:13,16:38,16:38,19:12,19:12,20:27,20:27
24,2024-12-24,06:03,06:02,13:16,13:14,16:38,16:38,19:13,19:12,20:28,20:27
25,2024-12-25,06:03,06:02,13:16,13:14,16:39,16:39,19:13,19:13,20:28,20:28
26,2024-12-26,06:04,06:03,13:17,13:15,16:39,16:39,19:14,19:13,20:29,20:28
27,2024-12-27,06:04,06:03,13:17,13:15,16:40,16:39,19:14,19:14,20:29,20:29
28,2024-12-28,06:05,06:04,13:18,13:16,16:40,16:40,19:15,19:14,20:30,20:29
29,2024-12-29,06:05,06:04,13:18,13:16,16:41,16:40,19:15,19:15,20:30,20:30
30,2024-12-30,06:06,06:05,13:19,13:17,16:41,16:41,19:16,19:15,20:30,20:30
31,2024-12-31,06:06,06:05,13:19,13:17,16:42,16:41,19:16,19:16,20:31,20:30

In [3]:
combinationTable.to_csv("DM1_timestamps.csv")

In [4]:
combinedDF = pd.read_csv("DW_prayer_times.csv")
combinedDF = combinedDF.loc[2525:2556,:].reset_index(drop=True)

# comparison = google - esolat | negative = error | positive = acceptable, as long as <= 2 mins
compareFajr = combinedDF["google_fajr"] - combinedDF["esolat_fajr"]
compareZuhr = combinedDF["google_zuhr"] - combinedDF["esolat_zuhr"]
compareAsr = combinedDF["google_asr"] - combinedDF["esolat_asr"]
compareMaghrib = combinedDF["google_maghrib"] - combinedDF["esolat_maghrib"]
compareIsha = combinedDF["google_isha"] - combinedDF["esolat_isha"]

compareDF = pd.DataFrame([combinedDF["date"],compareFajr,compareZuhr,compareAsr,compareMaghrib,compareIsha]).transpose()
compareDF.columns = ["date","diff_fajr","diff_zuhr","diff_asr","diff_maghrib","diff_isha"]

compareDF

          date diff_fajr diff_zuhr diff_asr diff_maghrib diff_isha
0   2024-11-30         0        -2        0            0         0
1   2024-12-01         0        -2       -1            0        -1
2   2024-12-02        -1        -1        0           -1         0
3   2024-12-03         0        -2        0            0         0
4   2024-12-04         0        -2        0           -1        -1
5   2024-12-05        -1        -2        0           -1         0
6   2024-12-06         0        -2       -1            0        -1
7   2024-12-07        -1        -2        0           -1         0
8   2024-12-08         0        -2       -1            0        -1
9   2024-12-09         0        -2        0           -1         0
10  2024-12-10        -1        -2        0            0        -1
11  2024-12-11         0        -2        0            0         0
12  2024-12-12        -1        -2        0           -1        -1
13  2024-12-13         0        -2        0            0         0
14  2024-12-14        -1        -2        0           -1        -1
15  2024-12-15         0        -2        0            0         0
16  2024-12-16        -1        -2        0           -1        -1
17  2024-12-17        -1        -2        0            0         0
18  2024-12-18        -1        -2        0           -1        -1
19  2024-12-19        -1        -2        0            0         0
20  2024-12-20        -1        -2        0           -1        -1
21  2024-12-21        -1        -2        0            0         0
22  2024-12-22        -1        -2        0           -1        -1
23  2024-12-23        -1        -2        0            0         0
24  2024-12-24        -1        -2        0           -1        -1
25  2024-12-25        -1        -2        0            0         0
26  2024-12-26        -1        -2        0           -1        -1
27  2024-12-27        -1        -2       -1            0         0
28  2024-12-28        -1        -2        0           -1        -1
29  2024-12-29        -1        -2       -1            0         0
30  2024-12-30        -1        -2        0           -1         0
31  2024-12-31        -1        -2       -1            0        -1

In [5]:
compareDF.to_csv("DM1_diffmins.csv")

In [6]:
def showStatisticsEvaluation(df1 = [], df2 = []):
    if (len(df1) == 0 or len(df2) == 0 or len(df1) != len(df2)):
        return print("Invalid data inputs!")
    
    eval_r2 = R2(df1,df2)
    eval_mae = MAE(df1,df2)
    eval_rmse = sqrt(MSE(df1,df2))
    eval_t = t_Test(df1,df2)[1]
    eval_F = f_Test(df1,df2)[1]

    print("--==================================--")
    print("Statistics Evaluation for Accuracy")
    print(f"R\u00b2 = {eval_r2:.6f}")
    print(f"MAE = {eval_mae:.6f}")
    print(f"RMSE = {eval_rmse:.6f}")
    print(f"t-Test (p-value) = {eval_t:.6f}")
    print(f"F-test (p-value) = {eval_F:.6f}")
    print("--==================================--")

In [7]:
print("Comparing e-Solat JAKIM vs Google Search results page - Fajr prayer time")
showStatisticsEvaluation(combinedDF["esolat_fajr"], combinedDF["google_fajr"])

Comparing e-Solat JAKIM vs Google Search results page - Fajr prayer time
--==================================--
Statistics Evaluation for Accuracy
R² = 0.963868
MAE = 0.687500
RMSE = 0.829156
t-Test (p-value) = 0.523836
F-test (p-value) = 0.523836
--==================================--

In [8]:
print("Comparing e-Solat JAKIM vs Google Search results page - Zuhr prayer time")
showStatisticsEvaluation(combinedDF["esolat_zuhr"], combinedDF["google_zuhr"])

Comparing e-Solat JAKIM vs Google Search results page - Zuhr prayer time
--==================================--
Statistics Evaluation for Accuracy
R² = 0.798783
MAE = 1.968750
RMSE = 1.976424
t-Test (p-value) = 0.081984
F-test (p-value) = 0.081984
--==================================--

In [9]:
print("Comparing e-Solat JAKIM vs Google Search results page - Asr prayer time")
showStatisticsEvaluation(combinedDF["esolat_asr"], combinedDF["google_asr"])

Comparing e-Solat JAKIM vs Google Search results page - Asr prayer time
--==================================--
Statistics Evaluation for Accuracy
R² = 0.990305
MAE = 0.187500
RMSE = 0.433013
t-Test (p-value) = 0.866768
F-test (p-value) = 0.866768
--==================================--

In [10]:
print("Comparing e-Solat JAKIM vs Google Search results page - Maghrib prayer time")
showStatisticsEvaluation(combinedDF["esolat_maghrib"], combinedDF["google_maghrib"])

Comparing e-Solat JAKIM vs Google Search results page - Maghrib prayer time
--==================================--
Statistics Evaluation for Accuracy
R² = 0.974662
MAE = 0.468750
RMSE = 0.684653
t-Test (p-value) = 0.668900
F-test (p-value) = 0.668900
--==================================--

In [11]:
print("Comparing e-Solat JAKIM vs Google Search results page - Isha prayer time")
showStatisticsEvaluation(combinedDF["esolat_isha"], combinedDF["google_isha"])

Comparing e-Solat JAKIM vs Google Search results page - Isha prayer time
--==================================--
Statistics Evaluation for Accuracy
R² = 0.976994
MAE = 0.468750
RMSE = 0.684653
t-Test (p-value) = 0.683255
F-test (p-value) = 0.683255
--==================================--